### ISSUE TITLE
Font family does not apply on options "Buttons"

### ISSUE THREAD

**Issue by mabusaa** [watson-developer-cloud/assistant-web-chat#1]
When you specify your font in Watson Portal , all Text seems taking the font family correctly ,  except the options "Buttons". 

![image](https://user-images.githubusercontent.com/13915373/66987244-0edd7d00-f0c9-11e9-8efb-721e30c460c4.png)

**Comment by ethanwinters** [comment]
Hi @mabusaa this issue has been resolved in latest release.
